### ISSUE TITLE
Unable to access the frontend. 

### ISSUE THREAD

**Issue by josuemotte** [streamnative/pulsar-manager#150]
Hello, 

I'm currently trying to run this : https://streamnative.io/docs/v1.0.0/configure/control-center/pulsar-manager

I did a baremetal setup without too much issue by following this https://streamnative.io/docs/v1.0.0/install-and-upgrade/bare-metal/ubuntu and now I would like to run the pulsar-manager but I'm getting stuck with only access to the backend and the HerdDB 

```Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      609/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      698/sshd: /usr/sbin
tcp        0    340 10.0.0.227:22      10.0.0.43:58520    ESTABLISHED 7853/sshd: userdemo
tcp        0      0 10.0.0.227:22      10.0.0.43:58484    ESTABLISHED 7697/sshd: userdemo
tcp        0      0 10.0.0.227:22      10.0.0.43:57657    ESTABLISHED 842/sshd: userdemo
tcp        0      0 10.0.0.227:22      10.0.0.43:58297    ESTABLISHED 6770/sshd: userdemo
tcp6       0      0 :::7750                 :::*                    LISTEN      13221/java
tcp6       0      0 :::22                   :::*                    LISTEN      698/sshd: /usr/sbin
tcp6       0      0 127.0.0.1:7000          :::*                    LISTEN      13221/java
udp        0      0 127.0.0.53:53           0.0.0.0:*                           609/systemd-resolve
udp        0      0 10.0.0.227:68      0.0.0.0:*                           599/systemd-network
```
I was able to run the below command without any issue 
``` 
curl -H "Content-Type: application/json" -X PUT http://10.0.0.227:7750/pulsar-manager/users/superuser -d '{"name": "admin", "password": "apachepulsar", "description": "test", "email": "username@test.org"}'
```
Am I missing something ? 
Thanks

**Comment by sijie** [comment]
@tuteng Can you take a look at this issue?

**Comment by tuteng** [comment]
You can try to open the window in the browser and visit the site http://10.0.0.227:9527 @josuemotte

**Comment by tuteng** [comment]
I'm very sorry. I read the document, but it seems that there are some steps missing. At present, you can refer to this https://github.com/apache/pulsar-manager/wiki/Release-Candidate-Validation#start-pulsar-manager-frontend-service to set up the front end. 

You can use the following command to generate dist folder, and we will repair the document as soon as possible:

```
cd pulsar-manager/front-end
npm install --save
npm run build:prod
```

**Comment by josuemotte** [comment]
@tuteng 

Indeed it works now :-) thanks 

![image](https://user-images.githubusercontent.com/38882772/86247162-5d29a200-bbac-11ea-8d56-3d9b8fc62c25.png)
