### ISSUE TITLE
Investigate using HerdDB as backend SQL database

### ISSUE THREAD

**Issue by eolivelli** [streamnative/pulsar-manager#177]
HerdDB (https://github.com/diennea/herdddb) is an SQL database that is built upon Apache BookKeeper and Apache ZooKeeper.
When you have a Pulsar cluster you already have Bookies and a ZK cluster so setting up an HerdDB database is simple.
HerdDB has a JDBC client as primary client interface and it was originally developed to replace MySQL.

HerdDB server can run inside the same process of the client application, supported modes:
- in memory only, for tests and demos
- standalone: data, WAL and metadata on local disk (separate process or embedded into the client JVM)
- cluster: WAL on BK, metadata on ZK, data on local disk (separate process or embedded into the client JVM)

In case of cluster mode + embedded mode one of the client applications will accept write requests, the selection of this "leader" JVM is by default static in order to have full control over resource usages, but there are mechanisms to elect automatically to other nodes in cause of permanent failure

The change should be quite simple following PR #164 (MySQL support).

**Comment by eolivelli** [comment]
Good news:
I am able to start Pulsar Manager with HerdDB, just by adding the JDBC driver and creating the sql file for creating the schema.

But I have one problem, HerdDB uses "Apache Calcite" for parsing SQL and it does not deal well with column names named 'timestamp'.

I am trying to find a workaround but queries are hardcoded in .java files so it won't be easy to use a different columnname or to "escape" the columnname

**Comment by tuteng** [comment]
It is resolved here https://github.com/streamnative/pulsar-manager/pull/194.
